apiVersion: skaffold/v1beta2
kind: Config
build:
  local: # this means don't push to your git repo
    push: false # when the setting is set to false.
  artifacts:
    - image: rwuniard/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": . # This means detect any javascript changes and copy it to target in kubernetes
        "**/*.css": .
        "**/*.html": .
    - image: rwuniard/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
    - image: rwuniard/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
      - k8s/server-cluster-ip-service.yaml
